name: Build and deploy Python app to Azure Web App

env:
  WEBAPP_NAME: openai-whisper-react-demo
  CONDA_ENV_NAME: openai-env
  CONDA_PYTHON_VERSION: '3.7'
  CONDA_CHANNELS: conda-forge
  CONDA_DEPENDENCIES: pip

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: actions/setup-miniconda@v1
        with:
          miniconda-version: 'latest'

      - name: Create Conda environment
        run: |
          conda create --name ${{ env.CONDA_ENV_NAME }} python=${{ env.CONDA_PYTHON_VERSION }} -y
          conda activate ${{ env.CONDA_ENV_NAME }}
          conda config --add channels ${{ env.CONDA_CHANNELS }}
          conda install ${{ env.CONDA_DEPENDENCIES }} -y

      - name: Install Python packages
        run: |
          pip install -r backend/requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/
